# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('view_count', models.IntegerField(db_index=True, default=0)),
                ('signature', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
