# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='', max_length=50),
        ),
    ]
